# -*- coding: utf-8 -*-
"""Book_Reccomendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O5r7YUoNfb_dRb5iHNdGPJefv5hilP1P
"""

class BookRecommendationSystem:
    def __init__(self):
        self.books = {
            'The Catcher in the Rye': {'genre': 'Fiction', 'rating': 4.1},
            'To Kill a Mockingbird': {'genre': 'Classics', 'rating': 4.3},
            'The Hunger Games': {'genre': 'Young Adult', 'rating': 4.2},
            '1984': {'genre': 'Science Fiction', 'rating': 4.4},
            'Pride and Prejudice': {'genre': 'Romance', 'rating': 4.5}
        }
        self.user_preferences = {}

    def recommend_book(self):
        genre_preference = input("Enter your preferred book genre (Fiction, Classics, Young Adult, etc.): ").strip().capitalize()
        filtered_books = [book for book, details in self.books.items() if details['genre'] == genre_preference]

        if not filtered_books:
            print(f"Sorry, no books found in the {genre_preference} genre.")
            return

        print(f"Recommended books in the {genre_preference} genre:")
        for book in filtered_books:
            print(f"- {book}")

    def rate_book(self):
        book_to_rate = input("Enter the book you'd like to rate: ").strip()
        if book_to_rate in self.books:
            rating = float(input(f"Rate '{book_to_rate}' (0.0 to 5.0): "))
            if 0.0 <= rating <= 5.0:
                self.books[book_to_rate]['rating'] = rating
                print(f"Thank you for rating '{book_to_rate}'!")
            else:
                print("Invalid rating. Please enter a number between 0.0 and 5.0.")
        else:
            print(f"Book '{book_to_rate}' not found in the database.")

    def run_recommendation_system(self):
        while True:
            print("\n===== Book Recommendation System =====")
            print("1. Recommend a book based on genre")
            print("2. Rate a book")
            print("3. Exit")
            choice = input("Enter your choice (1/2/3): ").strip()

            if choice == '1':
                self.recommend_book()
            elif choice == '2':
                self.rate_book()
            elif choice == '3':
                print("Exiting Book Recommendation System. Goodbye!")
                break
            else:
                print("Invalid choice. Please enter 1, 2, or 3.")

# Example usage
if __name__ == "__main__":
    recommendation_system = BookRecommendationSystem()
    recommendation_system.run_recommendation_system()